# Gradle launcher (self-bootstrapping; no pre-installed Gradle needed)
#
# Why this exists: this machine has no Gradle and no gradle wrapper (the wrapper jar
# has to be generated by an existing Gradle first). This script downloads a pinned
# Gradle distribution into a cache dir and reuses it afterwards - equivalent to a
# wrapper, but with no binary committed to the repo.
#
# NOTE: comments and output in this file are intentionally ASCII-only.
# Windows PowerShell 5.1 reads .ps1 files as the system ANSI codepage (GBK here)
# unless there is a UTF-8 BOM. Non-ASCII text without a BOM gets mangled and can
# break string literals. ASCII is immune to that whole class of problem.
#
# Usage:
#   powershell -File tools/gradle.ps1 :app:assembleDebug
#   powershell -File tools/gradle.ps1 :app:testDebugUnitTest
#   powershell -File tools/gradle.ps1 --version

param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$GradleArgs
)

$ErrorActionPreference = "Stop"

$GradleVersion = "8.9"
$CacheRoot     = "D:\DevEnv\gradle"
$GradleHome    = Join-Path $CacheRoot "gradle-$GradleVersion"
$DistUrl       = "https://services.gradle.org/distributions/gradle-$GradleVersion-bin.zip"
$JdkHome       = "D:\DevEnv\Java\jdk21"

# ---------- Gradle itself (bootstrap) ----------
if (-not (Test-Path (Join-Path $GradleHome "bin\gradle.bat"))) {
    Write-Host "==> First run: downloading Gradle $GradleVersion ..."
    New-Item -ItemType Directory -Force -Path $CacheRoot | Out-Null
    $zip = Join-Path $CacheRoot "gradle-$GradleVersion-bin.zip"
    if (-not (Test-Path $zip)) {
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        Invoke-WebRequest -Uri $DistUrl -OutFile $zip -UseBasicParsing
        $sw.Stop()
        Write-Host ("==> Downloaded {0:N1} MB in {1:N0}s" -f ((Get-Item $zip).Length/1MB), $sw.Elapsed.TotalSeconds)
    }
    Expand-Archive -Path $zip -DestinationPath $CacheRoot -Force
    Write-Host "==> Gradle ready: $GradleHome"
}

# ---------- JDK ----------
if (-not (Test-Path $JdkHome)) { throw "JDK not found: $JdkHome" }
$env:JAVA_HOME = $JdkHome

# ---------- Android SDK ----------
$projRoot   = Split-Path $PSScriptRoot -Parent
$localProps = Join-Path $projRoot "local.properties"
if (-not (Test-Path $localProps)) {
    Write-Warning "local.properties is missing. Run tools\setup-android-sdk.ps1 first, or Gradle cannot find the Android SDK."
}

# ---------- Run ----------
if (-not $GradleArgs -or $GradleArgs.Count -eq 0) { $GradleArgs = @("tasks") }

# Two things matter here:
#
# 1. gradle.bat is invoked through cmd.exe so that stderr is merged into stdout
#    *inside* the batch process. Without this, PowerShell wraps each stderr line
#    in a NativeCommandError record and the Kotlin compiler's error text gets
#    truncated in the middle of the message - which is exactly where the useful
#    part is.
# 2. ErrorActionPreference is relaxed to Continue for the same reason: with
#    "Stop", the first stderr line aborts before the rest is collected.
$ErrorActionPreference = "Continue"

$quotedArgs = ($GradleArgs | ForEach-Object { '"' + $_ + '"' }) -join ' '
$cmd = '""' + (Join-Path $GradleHome "bin\gradle.bat") + '" ' + $quotedArgs + ' --console=plain 2>&1"'

Write-Host "==> gradle $($GradleArgs -join ' ')"
& cmd.exe /c $cmd
$code = $LASTEXITCODE
exit $code
